--- 
- hosts: localhost
  vars:
    state: present
    s3_bucket: terraformjenkyjawnt
    key: terraform.tfstate
    region: us-east-1
    app_env: dev 
  tasks:

  - name:
    dynamodb_table:
      name: dynamojawnt
      region: "{{ region }}"
      state: "{{ state }}"
      hash_key_name: LockID
      hash_key_type: STRING 
      read_capacity: 2
      write_capacity: 2


  - name: runs terraform scripts
    terraform:
      project_path: "./"
      state: present
      backend_config:
          bucket: "{{ s3_bucket }}"
          key: "{{ key }}"
          region: "{{ region }}"
      variables_file: "{{ app_env }}.tfvars"
      workspace: "{{ app_env }}"
  
       